In [1]:
import numpy as np
import math
import scipy as s

In [2]:
def energie(masse,hauteur, energie_limit, g=9.81):
    e= masse*hauteur*g
    if e<energie_limit:
        print(f"l'eneregie {e} est inférieure à l'eneregie limite {energie_limit}/n")

    else:
        print(f"l'eneregie {e} est supérieure à l'energie limite {energie_limit}")

    return(f"{e} Joules")



In [3]:
energie(80,20,100,10)

l'eneregie 16000 est supérieure à l'energie limite 100


'16000 Joules'

In [4]:
#manipulation de liste
a=list()
a=['guy','martial', 'aude']
a.append('marseilles')
print(a)

for i,j in enumerate(a):


    print(i,j)
       

['guy', 'martial', 'aude', 'marseilles']
0 guy
1 martial
2 aude
3 marseilles


In [5]:
a.count('guy')
a.insert(2,'mimi')
print(a)
a.reverse()
print(a)
a.sort()

['guy', 'martial', 'mimi', 'aude', 'marseilles']
['marseilles', 'aude', 'mimi', 'martial', 'guy']


In [6]:
def fibo(n):
    a=[]
    b=[]
    a=0
    b=1
    while a<n:
        print(a)
        a, b=b, a+b
        

In [7]:
fibo(1000)
type(a)
len(a)

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987


5

In [8]:
a=["ari",2,8,9,"orrr"]
b=[2,7,9,87]

for i, j in zip(a,b):
    print(i==j)

False
False
False
False


In [9]:
classeur={
    "positif":[],
    "negatif":[]

}

In [10]:
def trier(classeur, nbr):
    if nbr<0:
        classeur["negatif"].append(nbr)
    else:
        classeur["positif"].append(nbr)
        return classeur

In [11]:
trier(classeur,4)

print(classeur["positif"][0])



4


In [12]:
tpl=()
tpl=(2,"guy",7)

print(tpl)
#tpl[0]=79
print(tpl)

(2, 'guy', 7)
(2, 'guy', 7)


In [13]:
dico={k**2:v for k,v in enumerate(range(21))}
#dico2={k**2:v for k,v in enumerate(range(21)) if }
#dico2={k**2 for k in range(21)}
dico2={k:v for k, v in dico.items() if v%2==0}
list_1=[k**2 for k in range(21)]
#print(dico)
#print(list_1)
print(dico2)



{0: 0, 4: 2, 16: 4, 36: 6, 64: 8, 100: 10, 144: 12, 196: 14, 256: 16, 324: 18, 400: 20}


In [14]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,2,3])
a.argsort() 
print(a)
#a.argmax(axis=0)
a.argmax(axis=1)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 2, 2])

In [15]:
np.random.seed(0)
c=np.random.randint(0,100,[10,5])
moy=c.mean(axis=0)
ety=c.std(axis=0)

In [1]:
a=1
b=6
print(a+b*22)

133
